#ifndef _BASICTYPES_H_
#define _BASICTYPES_H_

typedef enum RET_TYPE
{
    RET_OK = 0,
    RET_EXEC_FAIL,

} RetType_e;

/* JESD-SERDES Related */
#define AFE_NUM_RX_CHANNELS 4
#define AFE_NUM_RX_CHANNELS_BITWISE 0xf
#define AFE_NUM_BANDS_PER_RX 2

#define AFE_NUM_TX_CHANNELS 4
#define AFE_NUM_TX_CHANNELS_BITWISE 0xf
#define AFE_NUM_BANDS_PER_TX 2

#define AFE_NUM_FB_CHANNELS 2
#define AFE_NUM_FB_CHANNELS_BITWISE 0x3
#define AFE_NUM_BANDS_PER_FB 1

#define AFE_NUM_JESD_INSTANCES 2
#define AFE_NUM_CH_PER_JESD_INSTANCE 2
#define AFE_NUM_SERDES_LANES 8

#define jesdToSerdesLaneMapping \
    {                           \
        1, 0, 2, 3, 3, 2, 0, 1  \
    }

/*PAGE INFO*/
#define AFE_PAGE_START_ADDR 0x10
#define AFE_PAGE_END_ADDR 0x19

/*  MACRO ERROR STATUS TYPES   */
#define AFE_MACRO_NO_ERROR 0
#define AFE_MACRO_ERROR_IN_OPCODE 1
#define AFE_MACRO_ERROR_OPCODE_NOT_ALLOWED 2
#define AFE_MACRO_ERROR_IN_OPERAND 4
#define AFE_MACRO_ERROR_IN_EXECUTION 8

/*  MACRO STATUS ADDRESS INFO   */
#define AFE_MACRO_STATUS_REG_ADDR 0xF0
#define AFE_MACRO_OPCODE_REG_ADDR 0x193
#define AFE_MACRO_EXTENDED_ERROR_CODE_REG_ADDR 0xF2
#define AFE_MACRO_RESULT_START_REG_ADDR 0xF8
#define AFE_MACRO_OPERAND_START_REG_ADDR 0xA0
#define AFE_MACRO_PAGE_REG_ADDR 0x18
#define AFE_MACRO_PAGE_SEL_VAL 0x20

/*  MACRO OPCODES   */
#define AFE_MACRO_OPCODE_SYSTEM_TUNE 0x90
#define AFE_MACRO_OPCODE_PREPARE_FOR_TUNE 0x35
#define AFE_MACRO_OPCODE_SYSTEM_TUNE_SELECTIVE 0x36
#define AFE_MACRO_OPCODE_UPDATE_SYSTEM_TX_CHANNEL_FREQUENCY_CONFIGURATION 0x37
#define AFE_MACRO_OPCODE_UPDATE_TX_DIG_PARAM 0x50
#define AFE_MACRO_OPCODE_UPDATE_TX_GAIN 0x51
#define AFE_MACRO_OPCODE_UPDATE_SYSTEM_RX_CHANNEL_FREQUENCY_CONFIGURATION 0x38
#define AFE_MACRO_OPCODE_UPDATE_SYSTEM_FB_CHANNEL_FREQUENCY_CONFIGURATION 0x39
#define AFE_MACRO_OPCODE_APPLY_DSA_GAIN_PHASE_COMPENSATION 0x11
#define AFE_MACRO_OPCODE_UPDATE_SYSTEM_TX_CHANNEL_FREQUENCY_CONFIGURATION_ALL_BANDS 0x3E
#define AFE_MACRO_OPCODE_FACTORY_RX_DSA_GAIN_PHASE_CALIBRATION 0x41
#define AFE_MACRO_OPCODE_FACTORY_TX_DSA_GAIN_PHASE_CALIBRATION 0x42
#define AFE_MACRO_OPCODE_CONFIG_SIGGEN_FOR_CAL 0x48
#define AFE_MACRO_OPCODE_AGC_STATE_CONTROL 0x68
#define AFE_MACRO_OPCODE_AGC_DIG_DET_CONFIG 0x58
#define AFE_MACRO_OPCODE_AGC_DET_TIME_CONST_CONFIG 0x59
#define AFE_MACRO_OPCODE_AGC_DIG_DET_ABSOLUTE_NUM_CROSSINGS_CONFIG 0x5B
#define AFE_MACRO_OPCODE_AGC_DIG_DET_RELATIVE_NUM_CROSSINGS_CONFIG 0x5A
#define AFE_MACRO_OPCODE_EXT_AGC_CONFIG 0x5C
#define AFE_MACRO_OPCODE_INT_AGC_CONTROLLER_CONFIG 0x5E
#define AFE_MACRO_OPCODE_MIN_MAX_DSA_ATTN_CONFIG 0x5F
#define AFE_MACRO_OPCODE_AGC_EXT_LNA_CONFIG 0x61
#define AFE_MACRO_OPCODE_AGC_EXT_LNA_GAIN_CONFIG 0x66
#define AFE_MACRO_OPCODE_AGC_GAIN_STEP_SIZE_CONFIG 0x67
#define AFE_MACRO_OPCODE_AGC_RF_ANALOG_CONFIG 0x65
#define AFE_MACRO_OPCODE_ALC_CONFIGURATION 0x69
#define AFE_MACRO_OPCODE_FLOATING_POINT_CONFIG_ALC 0x6A
#define AFE_MACRO_OPCODE_COARSE_FINE_MODE_ALC 0x6B

/* DSA Related */
#define AFE_RX_DSA_MAX_ANA_DSA_DB 25
#define AFE_TX_DSA_MAX_ANA_DSA_DB 34
#define AFE_FB_DSA_MAX_ANA_DSA_DB 25

#define AFE_RX_DSA_MAX_ANA_DSA_INDEX 50
#define AFE_RX_DSA_MAX_DIG_DSA_INDEX 47
#define AFE_TX_DSA_MAX_ANA_DSA_INDEX 29
#define AFE_FB_DSA_MAX_ANA_DSA_INDEX 50

#define AFE_TX_DSA_MAX_ANA_PLUS_DIG_DSA_DB 39

/* AGC Related */
#define AFE_AGC_MAX_WIN_LEN 4000000
#define AFE_AGC_MAX_ABS_NUM_HITS 0xffffff

#ifndef NULL
#define NULL (0)
#endif

#endif /* _BASICTYPES_H_ */
